protocol:
  hub: 26
  stablecoin: "0x66a6d929663EADEDf5E628334F280d5D64F16966"
  staking: "0x741F2E9ade5B68B7eEd8729a2Ec6B2F051Fd2C05"
networks:
  - name: "arc"
    domain: 26
    rpc_url: "https://rpc.testnet.arc.network"
    vault: "0x66a6d929663EADEDf5E628334F280d5D64F16966"
  - name: "ethereum"
    domain: 0
    rpc_url: "https://ethereum-sepolia-rpc.publicnode.com"
  - name: "base"
    domain: 6
    rpc_url: "https://base-sepolia-rpc.publicnode.com"
  - name: "avalanche"
    domain: 1
    rpc_url: "https://avalanche-fuji-c-chain-rpc.publicnode.com"

    
    
  