protocol:
  hub: 26
  stablecoin: "0x851addF749C87F1159F30399F2ca160F8Ccdb6B1"
  staking: "0xA4c3C583432A34f812A5307fA6a8A4ec6D529Fc0"
networks:
  - name: "arc"
    domain: 26
    rpc_url: "https://rpc.testnet.arc.network"
    vault: "0x851addF749C87F1159F30399F2ca160F8Ccdb6B1"
  - name: "ethereum"
    domain: 0
    rpc_url: "https://ethereum-sepolia-rpc.publicnode.com"
  - name: "base"
    domain: 6
    rpc_url: "https://base-sepolia-rpc.publicnode.com"
  - name: "avalanche"
    domain: 1
    rpc_url: "https://avalanche-fuji-c-chain-rpc.publicnode.com"

    
    
  