services:
  db:
    image: timescale/timescaledb:latest-pg15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0681d7bf4e0c
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  eventscale:
    image: eventscale:0.1.3
    restart: always
    command: ["-c", "/eventscale/conf/config.yaml"]
    volumes:
      - ./nats.conf:/eventscale/conf/nats.conf
      - ./eventscale.yaml:/eventscale/conf/config.yaml
  backend:
    image: terrace-backend:0.1.0
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - eventscale

volumes:
 db_data: