services:
  db:
    image: timescale/timescaledb:latest-pg15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0681d7bf4e0c
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  eventscale:
    image: eventscale:0.1.3
    command: ["-c", "/eventscale/conf/config.yaml"]
    ports:
      - "4222:4222"
    volumes:
      - ./nats.conf:/eventscale/conf/nats.conf
      - ./eventscale.yaml:/eventscale/conf/config.yaml

volumes:
 db_data: