[project]
src = "src"
out = "out"
dot_env = ".env"
dependencies = ["snekmate"]

[networks.pyevm]
is_zksync = false

[networks.arc]
url = "https://rpc.testnet.arc.network"
explorer_uri = "https://testnet.arcscan.app/"
explorer_type = "blockscout"
chain_id = 5042002
fork = false

[networks.arc.contracts]
usdc = {"address" = "0x3600000000000000000000000000000000000000"}
messanger = {"address" = "0x8FE6B999Dc680CcFDD5Bf7EB0974218be2542DAA"}
transmitter = {"address" = "0xE737e5cEBEEBa77EFE34D4aa090756590b1CE275"}

[networks.arc.extra_data]
withdrawal_delay = 30
hub_domain = 26

[networks.contracts]
stablecoin = {  deployer_script = "script/deploy_stablecoin.py" }
vault = {  deployer_script = "script/deploy_vault.py" }